USE EVENT_QUEUE;
GO 
-- TABLES
IF OBJECT_ID ('EVENTS_Q','U')IS NOT NULL
	DROP TABLE EVENTS_Q;
GO
CREATE TABLE EVENTS_Q
(
	id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	txt VARCHAR(100)
)
GO 
-- PROCEDURES
IF  OBJECT_ID ('MASSUPDATE','P')IS NOT NULL
	DROP PROCEDURE MASSUPDATE;
GO 
CREATE PROCEDURE MASSUPDATE 
AS
	INSERT INTO EVENTS_Q(txt)VALUES('TEST')
	SELECT * FROM EVENTS_Q
GO 
-- TRGIGGERS
IF OBJECT_ID ('EVENTS_QMODIFIED','TR')IS NOT NULL
	DROP TRIGGER EVENTS_QMODIFIED;
GO 
CREATE TRIGGER EVENTS_QMODIFIED
	ON EVENTS_Q
	AFTER INSERT
AS
	DECLARE @ID AS INT,
		@TXT AS VARCHAR(100);
	SELECT @TXT=(txt++'_AFTER_TRIGGER'),@ID=id FROM INSERTED;
	UPDATE EVENTS_Q SET txt=@TXT WHERE id=@ID;
GO
